language: python
matrix:
    include:
        - os: linux
          python: 3.5 
        - os: linux
          python: 3.6
        - os: linux
          python: "nightly"
        - os: osx
          python: 3.4
        - os: osx
          python: 3.5
        - os: osx
          python: 3.6
    allow_failures:
        - python: "nightly"

install:
  - pip install -r requirements-tests.txt
  - python setup.py install

script:
  - py.test --flake8 --timeout=10 --cov=./slug
  - bash <(curl -s https://codecov.io/bash)

