language: python
env:
   global:
       - secure: "pvQHCsdcIRjwNvsBrZxP8cZWEwug0+PLg1T8841ZLkMdCaO3YheqmxF1xGjAqty6hLppz6vX1LFEKmPjKurLL0/i+be6MhT8/ZikFpSan7TdNUqISxeFx31ls+QpuFKzCV7ZEx7C1ms8LPWEGmzMMN6bCtOBVtGznD9KKWZmLlA="
matrix:
    include:
        - os: linux
          python: 3.5 
          env: 
            - MINICONDA_OS="Linux"
        - os: linux
          python: 3.6
          env: 
            - MINICONDA_OS="Linux"
        - os: linux
          python: "nightly"
        - os: osx
          language: generic
          env: PYTHON="3.4" MINICONDA_OS="MacOSX"
        - os: osx
          language: generic
          env: PYTHON="3.5" MINICONDA_OS="MacOSX"
        - os: osx
          language: generic
          env: PYTHON="3.6" MINICONDA_OS="MacOSX"
    allow_failures:
        - python: "nightly"

before_install:
  - URL="https://repo.continuum.io/miniconda/Miniconda3-latest-${MINICONDA_OS}-x86_64.sh";
    wget "${URL}" -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda;
    export PATH="$HOME/miniconda/bin:$PATH";
    hash -r;
    conda config --set always_yes yes --set changeps1 no;
    conda update -q conda;
    conda info -a;
  
install:
  - pip install -r requirements-tests.txt;

before_script:
  - rvm get head || true

script:
  - set -e
  - py.test --timeout=10;

