language: python
matrix:
    include:
        - os: linux
          python: 3.5 
        - os: linux
          python: 3.6
        - os: linux
          python: "nightly"
        - os: osx
          language: generic
        - os: osx
          language: generic
        - os: osx
          language: generic
    allow_failures:
        - python: "nightly"

install:
  - pip install -r requirements-tests.txt;

script:
  - py.test --flake8 --timeout=10 --cov=./slug;

